import { useState } from 'react';
import s from '../constants/styles';

export default function ContactPage({ fire }) {
 const [cf,setCf]=useState({name:"",email:"",phone:"",service:"",message:""});
 const [sent,setSent]=useState(false);
 return (
  <div>
   <div style={s.shopHero}><div style={s.inner}><div style={s.secLabel}>✦ GET IN TOUCH ✦</div><h1 style={s.shopH1}>Contact Us</h1><p style={s.shopSub}>We respond within 24 hours — let us know how we can help</p></div></div>
   <div style={{...s.inner,padding:"60px 24px"}}>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1.4fr",gap:48,alignItems:"start"}}>
     <div>
      <div style={{background:"linear-gradient(135deg,#1a0533,#2d1066)",borderRadius:20,padding:"36px",border:"1px solid rgba(201,150,63,0.2)"}}><h3 style={{fontFamily:"'Playfair Display',serif",fontSize:22,color:"#fff",marginBottom:28}}>Contact Information</h3>{[{icon:"✉",label:"Email",val:"support@lldhome.com",link:"mailto:support@lldhome.com"},{icon:"📞",label:"Phone",val:"+1 (210) 742-4957",link:"tel:+12107424957"},{icon:"◎",label:"Social",val:"@longlifedigital",link:"https://instagram.com/longlifedigital"},{icon:"🌐",label:"Website",val:"longlifedigital.co",link:"https://longlifedigital.co"}].map(({icon,label,val,link})=>(<a key={label} href={link} target="_blank" rel="noopener noreferrer" style={{display:"flex",alignItems:"center",gap:14,marginBottom:20,textDecoration:"none"}}><div style={{width:42,height:42,borderRadius:"50%",background:"linear-gradient(135deg,#C9963F,#E8C97A)",display:"flex",alignItems:"center",justifyContent:"center",color:"#1a0533",fontSize:16,flexShrink:0}}>{icon}</div><div><div style={{fontSize:10,letterSpacing:2,color:"#6D28D9",textTransform:"uppercase",marginBottom:3}}>{label}</div><div style={{fontSize:14,color:"#DDD6FE",fontWeight:500}}>{val}</div></div></a>))}<div style={{marginTop:28,paddingTop:20,borderTop:"1px solid rgba(201,150,63,0.15)"}}><div style={{fontSize:11,color:"#E8C97A",letterSpacing:1,marginBottom:8}}>⏱ RESPONSE TIME</div><div style={{fontSize:13,color:"#C084FC"}}>We reply to all messages within 24 hours, Monday through Saturday.</div></div></div>
     </div>
     <div style={{background:"#fff",borderRadius:20,padding:"36px",border:"1px solid rgba(201,150,63,0.15)",boxShadow:"0 8px 40px rgba(147,51,234,0.08)",position:"relative"}}>
      <div style={{position:"absolute",inset:0,borderRadius:20,border:"1.5px solid transparent",background:"linear-gradient(#fff,#fff) padding-box,linear-gradient(135deg,#C9963F,#E8C97A,#9333EA,#C084FC) border-box",pointerEvents:"none"}}/>
      {sent?(<div style={{textAlign:"center",padding:"40px 0"}}><div style={{fontSize:48,marginBottom:16}}>✦</div><h3 style={{fontFamily:"'Playfair Display',serif",fontSize:24,color:"#9333EA",marginBottom:12}}>Message Sent!</h3><p style={{color:"#9CA3AF",marginBottom:24}}>Thank you! We will reply within 24 hours.</p><button className="btn-h" style={s.btnPrimary} onClick={()=>setSent(false)}>Send Another</button></div>):(<div style={{position:"relative"}}><h3 style={{fontFamily:"'Playfair Display',serif",fontSize:20,color:"#1a0533",marginBottom:20}}>Send Us a Message</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div><label style={s.lbl}>Your Name *</label><input className="inp-f" style={s.inp} placeholder="John Smith" value={cf.name} onChange={e=>setCf({...cf,name:e.target.value})}/></div><div><label style={s.lbl}>Email *</label><input className="inp-f" style={s.inp} placeholder="john@email.com" value={cf.email} onChange={e=>setCf({...cf,email:e.target.value})}/></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div><label style={s.lbl}>Phone</label><input className="inp-f" style={s.inp} placeholder="+1 (555) 000-0000" value={cf.phone} onChange={e=>setCf({...cf,phone:e.target.value})}/></div><div><label style={s.lbl}>Service Interested In</label><select className="inp-f" style={s.inp} value={cf.service} onChange={e=>setCf({...cf,service:e.target.value})}><option value="">Select a service...</option>{["Affiliate Marketing","SEO","LLC Formation","Website Design","Social Media Management","Google Business","Facebook & Google Ads","AI Automation","Branding & Design","Digital Product Creation","Domain Purchase","Other"].map(sv=><option key={sv} value={sv}>{sv}</option>)}</select></div></div><label style={s.lbl}>Message *</label><textarea className="inp-f" style={{...s.inp,height:120,resize:"vertical"}} placeholder="Tell us about your project or question..." value={cf.message} onChange={e=>setCf({...cf,message:e.target.value})}/><button className="btn-h" style={{...s.btnPrimary,width:"100%",marginTop:16,padding:"14px"}} onClick={()=>{if(cf.name&&cf.email&&cf.message){setSent(true);fire("Message sent! We will reply within 24 hours. ✦");}else{fire("Please fill all required fields.","err");}}}>✦ Send Message</button></div>)}
     </div>
    </div>
   </div>
  </div>
 );
}
