import { useState } from 'react';
import s from '../constants/styles';

const DOMAIN_LISTINGS=[{name:"startup.io",cat:"Premium",price:"$2,500",desc:"4-year aged premium .io domain. Perfect for tech startups. High recall, short and memorable.",badge:"🔥 Hot"},{name:"AItools.co",cat:"AI-Related",price:"$1,800",desc:"Premium AI-focused domain perfect for AI product businesses and SaaS tools.",badge:"🤖 AI"},{name:"MarketingPro.com",cat:"Marketing",price:"$3,200",desc:"Authoritative .com domain for marketing agencies and consultants. High SEO potential.",badge:"⭐ Premium"},{name:"DenverHomes.co",cat:"Real Estate",price:"$899",desc:"Local real estate domain targeting Denver market. Great for agents and brokers.",badge:"🏠 Local"},{name:"QuickBrand.io",cat:"Brandable",price:"$650",desc:"Catchy brandable domain suitable for any startup or new brand. Clean and memorable.",badge:"✦ Brandable"},{name:"LocalBiz.co",cat:"Local",price:"$750",desc:"Versatile local business domain perfect for small business directories or agencies.",badge:"📍 Local"},{name:"AIPrompts.co",cat:"AI-Related",price:"$1,200",desc:"Highly relevant domain for AI prompt businesses, marketplaces and digital products.",badge:"🤖 AI"},{name:"SocialGrowth.com",cat:"Marketing",price:"$2,100",desc:"Premium marketing domain for social media agencies and growth consultants.",badge:"📈 Marketing"}];

export default function DomainsPage({ setPage }) {
 const [domFilter,setDomFilter]=useState("All");
 const domCats=["All","Premium","AI-Related","Marketing","Real Estate","Brandable","Local"];
 const filteredDomains=domFilter==="All"?DOMAIN_LISTINGS:DOMAIN_LISTINGS.filter(d=>d.cat===domFilter);
 return (
  <div>
   <div style={s.shopHero}><div style={s.inner}><div style={s.secLabel}>✦ PREMIUM DOMAINS ✦</div><h1 style={s.shopH1}>Domains For Sale</h1><p style={s.shopSub}>Premium, brandable and niche domains ready for immediate transfer</p></div></div>
   <div style={{...s.inner,padding:"40px 24px 60px"}}>
    <div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:36}}>{domCats.map(cat=>(<button key={cat} className="btn-h" style={{...s.filt,borderColor:domFilter===cat?"#9333EA":"#E8D5F5",color:domFilter===cat?"#9333EA":"#9CA3AF",background:domFilter===cat?"rgba(147,51,234,0.06)":"#fff"}} onClick={()=>setDomFilter(cat)}>{cat}</button>))}</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:24}}>{filteredDomains.map((d,i)=>(<div key={i} style={s.domainCard}><div style={{position:"absolute",top:0,left:0,right:0,height:3,background:"linear-gradient(90deg,#7C3AED,#C9963F,#E8C97A)"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:12}}><span style={{fontSize:10,background:"rgba(147,51,234,0.08)",color:"#9333EA",borderRadius:20,padding:"3px 10px",fontWeight:700}}>{d.cat}</span><span style={{fontSize:10,background:"rgba(201,150,63,0.1)",color:"#C9963F",borderRadius:20,padding:"3px 10px",fontWeight:700}}>{d.badge}</span></div><div style={{fontFamily:"'Playfair Display',serif",fontSize:22,fontWeight:700,color:"#1a0533",marginBottom:8}}>{d.name}</div><p style={{fontSize:13,color:"#6B7280",lineHeight:1.65,marginBottom:16}}>{d.desc}</p><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{fontFamily:"'Playfair Display',serif",fontSize:24,fontWeight:700,color:"#9333EA"}}>{d.price}</div><button className="btn-h" style={s.btnPrimary} onClick={()=>setPage("contact")}>Inquire →</button></div></div>))}</div>
    <div style={{marginTop:48,background:"linear-gradient(135deg,#1a0533,#2d1066)",borderRadius:20,padding:"40px",border:"1px solid rgba(201,150,63,0.2)"}}><h3 style={{fontFamily:"'Playfair Display',serif",fontSize:24,color:"#fff",marginBottom:10}}>Have a Domain to Sell?</h3><p style={{color:"#C084FC",fontSize:14,lineHeight:1.75,marginBottom:20}}>We also purchase quality domains. If you own a premium domain and want to sell it, contact us for a valuation.</p><button className="btn-h" style={{...s.btnGold}} onClick={()=>setPage("contact")}>Contact Us →</button></div>
   </div>
  </div>
 );
}
