import s from '../constants/styles';

export default function RefundPage() {
 return (
  <div>
   <div style={s.shopHero}><div style={s.inner}><h1 style={s.shopH1}>Refund Policy</h1><p style={s.shopSub}>Last updated: January 2024</p></div></div>
   <div style={{...s.inner,maxWidth:760,padding:"60px 24px"}}>
    <div style={{background:"linear-gradient(135deg,#1a0533,#2d1066)",borderRadius:16,padding:"28px",marginBottom:40,border:"1px solid rgba(201,150,63,0.25)",textAlign:"center"}}><div style={{fontSize:36,marginBottom:12}}>⚠️</div><h2 style={{fontFamily:"'Playfair Display',serif",fontSize:24,color:"#fff",marginBottom:10}}>All Sales Are Final</h2><p style={{color:"#C084FC",fontSize:15,lineHeight:1.75,maxWidth:500,margin:"0 auto"}}>Due to the digital nature of our products, all sales are final. We do not offer refunds on any digital products once the download link has been accessed or delivered.</p></div>
    {[["No Refund Policy on Digital Products","All digital products sold by Longlife Digital — including ebooks, templates, prompt packs, planners, worksheets, PLR bundles and digital downloads — are non-refundable. Once a digital product has been purchased and the download link has been delivered, the sale is final and no refunds will be issued."],["Why We Have This Policy","Digital products are delivered instantly and cannot be returned. Unlike physical goods, digital files can be copied and retained even after a refund is issued. To protect the integrity of our products and business, we maintain a strict no-refund policy on all digital purchases."],["Before You Purchase","We strongly encourage all customers to read the full product description, review what is included and ensure the product meets your needs before completing your purchase. If you have questions about a product before buying, contact us at support@lldhome.com — we are happy to help you make the right decision."],["Exceptions","Refunds will only be considered in the following rare circumstances: (1) You were charged multiple times for the same order due to a technical error, or (2) You never received your download link due to a technical issue on our end. In these cases, contact us within 48 hours with proof of the issue."],["Services","Service-based offerings (website design, SEO, social media management, branding) are governed by a separate service agreement. Deposits are non-refundable once work has commenced. Please review your service agreement carefully before signing."],["Domain Purchases","Domain purchases are strictly non-refundable once the transfer process has been initiated. Please verify all domain details carefully before completing your purchase."],["Contact Us Before Buying","If you are unsure about a product, please reach out before purchasing. We would rather help you find the right product than have an unhappy customer. Email: support@lldhome.com | Phone: +1 (210) 742-4957"]].map(([title,body])=>(<div key={title} style={{marginBottom:28,padding:"24px",background:"#FAFAFA",borderRadius:12,border:"1px solid #F3F4F6"}}><h3 style={{fontSize:17,fontWeight:700,color:"#1a0533",fontFamily:"'Playfair Display',serif",marginBottom:10}}>{title}</h3><p style={{color:"#6B7280",lineHeight:1.85,fontSize:14}}>{body}</p></div>))}
   </div>
  </div>
 );
}
