import s from '../constants/styles';

export default function ServicesPage({ setPage }) {
 return (
  <div>
   <div style={s.shopHero}><div style={s.inner}><div style={s.secLabel}>✦ WHAT WE OFFER ✦</div><h1 style={s.shopH1}>Our Services</h1><p style={s.shopSub}>Professional digital services to grow your business online</p></div></div>
   <div style={{...s.inner,padding:"60px 24px"}}>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:28}}>
     {[{icon:"🤝",title:"Affiliate Marketing",price:"From $299/mo",desc:"We set up and manage your affiliate program. Get other people promoting your products and services."},{icon:"🔍",title:"SEO Services",price:"From $499/mo",desc:"Complete SEO strategy to rank your website #1 on Google. Keyword research, on-page and off-page optimization."},{icon:"🏢",title:"LLC Formation Assistance",price:"From $199",desc:"We guide you through forming your LLC step by step. Business name search, articles of organization and more."},{icon:"💻",title:"Website Design",price:"From $799",desc:"Custom professional websites built to convert visitors into customers. Mobile-first, fast and beautiful."},{icon:"📱",title:"Social Media Management",price:"From $399/mo",desc:"Full social media management for Instagram, Facebook, TikTok and LinkedIn. Content creation and scheduling."},{icon:"📍",title:"Google Business Optimization",price:"From $299",desc:"Optimize your Google Business Profile to dominate local search. Photos, posts, reviews and more."},{icon:"📣",title:"Facebook & Google Ads",price:"From $499/mo",desc:"Results-driven paid advertising on Facebook, Instagram and Google. Ad creation, targeting and management."},{icon:"🤖",title:"AI Automation Services",price:"From $599",desc:"Automate repetitive business tasks using AI tools. Email automation, chatbot setup and workflow systems."},{icon:"🎨",title:"Branding & Graphic Design",price:"From $399",desc:"Professional brand identity including logo design, color palette, typography and brand guidelines."},{icon:"📦",title:"Digital Product Creation",price:"From $299",desc:"We create your digital products for you. Ebooks, courses, templates, prompt packs and more."}].map((svc,i)=>(<div key={i} style={s.serviceCard}><div style={s.serviceIconWrap}>{svc.icon}</div><h3 style={s.serviceTitle}>{svc.title}</h3><div style={s.servicePrice}>{svc.price}</div><p style={s.serviceDesc}>{svc.desc}</p><button className="btn-h" style={{...s.btnPrimary,width:"100%",marginTop:16}} onClick={()=>setPage("contact")}>Get Started →</button></div>))}
    </div>
    <div style={{textAlign:"center",marginTop:56,background:"#F3EEFF",borderRadius:20,padding:"40px",border:"1px solid rgba(147,51,234,0.15)"}}><h2 style={{fontFamily:"'Playfair Display',serif",fontSize:28,color:"#1a0533",marginBottom:12}}>Not Sure Which Service You Need?</h2><p style={{color:"#6B7280",marginBottom:24,fontSize:15,lineHeight:1.75}}>Book a free 15-minute consultation call and we will recommend the best strategy for your business.</p><button className="btn-h" style={s.btnPrimary} onClick={()=>setPage("contact")}>Book Free Consultation →</button></div>
   </div>
  </div>
 );
}
