import DOMPurify from 'dompurify';

// Preserve editorial content, but let the storefront own its presentation.
// Do not modify the returned markup before rendering it.
export function sanitizeRichText(html = '') {
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [
      'p',
      'br',
      'div',
      'span',
      'ul',
      'ol',
      'li',
      'strong',
      'b',
      'em',
      'i',
      'u',
      's',
      'del',
      'sup',
      'sub',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'a',
      'blockquote',
      'pre',
      'code',
      'hr',
      'figure',
      'figcaption',
      'img',
      'table',
      'caption',
      'thead',
      'tbody',
      'tfoot',
      'tr',
      'th',
      'td',
    ],
    ALLOWED_ATTR: [
      'href',
      'title',
      'src',
      'alt',
      'start',
      'reversed',
      'type',
      'value',
      'colspan',
      'rowspan',
      'scope',
    ],
    ALLOW_DATA_ATTR: false,
    ALLOW_ARIA_ATTR: false,
  });
}
